### ISSUE TITLE
If there is a validator key, it is used always even when connecting to a diff network

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-shell#100]
steps to repro: 
start local node e.g. via nearcore/scripts/start_local

near login to testnet
near new_project and deploy 
near view contractId whoSaidHi fails with 

rror:  Error: [-32000] Server error: account {localaccount} does not exist while viewing
    at JsonRpcProvider.sendJsonRpc (/Users/evgueniadegtiareva/near/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:50:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async JsonRpcProvider.query (/Users/evgueniadegtiareva/near/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:32:24)
    at async Account.fetchState (/Users/evgueniadegtiareva/near/near-shell/node_modules/nearlib/lib/account.js:33:23)
    at async Account.state (/Users/evgueniadegtiareva/near/near-shell/node_modules/nearlib/lib/account.js:39:9)
    at async Near.account (/Users/evgueniadegtiareva/near/near-shell/node_modules/nearlib/lib/near.js:35:9)
    at async Object.exports.callViewFunction (/Users/evgueniadegtiareva/near/near-shell/index.js:110:21)
    at async exitOnError (/Users/evgueniadegtiareva/near/near-shell/bin/near:8:5)

**Comment by janedegtiareva** [comment]
This is fixed.
