### ISSUE TITLE
call function fails

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-shell#117]
Steps to reproduce:

* **Start a node** Navigate to nearcore folder. Switch to staging branch. Pull it. Start a node with:
```bash
rm -rf testdir; ./scripts/start_unittest.py --local
```
* **Get most recent near-shell** Navigate to near-shell folder. Switch to staging. Install it:
```bash
rm -rf node_modules; npm install
```
* **Create new account** Where `/Users/zaver/Projects/nearcore` should be replaced to your path to nearcore folder.
```bash
./bin/near create_account status_message --masterAccount=test.near --homeDir=/Users/zaver/Projects/nearcore/testdir --nodeUrl=http://localhost:3030
```
* **Deploy smart contract** (get wasm file here: https://www.dropbox.com/s/gtg1ytn8vboe3gj/status_message.wasm?dl=0)
```bash
/bin/near deploy --accountId=status_message --wasmFile=/Users/zaver/Projects/near-runtime-rs/examples/status-message/res/status_message.wasm --homeDir=/Users/zaver/Projects/nearcore/testdir --nodeUrl=http://localhost:3030
```

* **Call a function on it**
```bash
./bin/near call status_message set_status "{\"message\": \"Hello\"}" --accountId=test.near --wasmFile=/Users/zaver/Projects/near-runtime-rs/examples/status-message/res/status_message.wasm --homeDir=/Users/zaver/Projects/nearcore/testdir --nodeUrl=http://localhost:3030
```

EXPECTED:

To get a meaningful output.

ACTUAL:

near-shell returns an error:
```bash
WARNING] Didn't find config at /Users/zaver/Projects/near-shell/src/config, using default shell config
Scheduling a call: status_message.set_status({"message": "Hello"}) with attached 1000000000 NEAR
Loaded master account test.near key from /Users/zaver/Projects/nearcore/testdir/validator_key.json with public key = 22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV
Error:  TypeError: Cannot read property 'length' of undefined
    at Object.getTransactionLastResult (/Users/zaver/Projects/near-shell/node_modules/nearlib/lib/providers/provider.js:14:32)
    at Object.exports.scheduleFunctionCall (/Users/zaver/Projects/near-shell/index.js:98:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async exitOnError (/Users/zaver/Projects/near-shell/bin/near:8:5)
```

* **Confirm that the state changed**. We want to make sure that the above error is about transaction status not being read correctly, while the contract call was actually correctly executed.
```bash
./bin/near view status_message get_status "{\"account_id\": \"test.near\"}" --accountId=test.near --wasmFile=/Users/zaver/Projects/near-runtime-rs/examples/status-message/res/status_message.wasm --homeDir=/Users/zaver/Projects/nearcore/testdir --nodeUrl=http://localhost:3030
```

OBSERVE:
```
Result: Hello
```

**Comment by janedegtiareva** [comment]
it appears to be fixed when pulling latest on everything, restarting node, nuking deps in shell, and retrying
