### ISSUE TITLE
Cryptic compilation error

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-shell#135]
```
[21:21:07] AssertionError: assertion failed
    at name (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:180:1)
    at r.parameterTypes (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6742:43)
    at r.hasDecorator [as compileCallExpression] (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:5893:25)
    at r.compileBinaryExpression [as compileExpression] (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2793:21)
    at r.Compiler [as compileExpressionStatement] (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1969:3)
    at r.compileEmptyStatement [as compileStatement] (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1713:21)
    at r.compileStatements (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1787:5)
    at r.currentFlow [as compileIfStatement] (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2135:10)
    at r.stmt [as compileStatement] (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1721:9)
    at r.compileStatements (/Users/vg/Documents/near-chess/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1787:5)
```

See https://github.com/nearprotocol/near-chess/tree/compile-fail for repro

**Comment by janedegtiareva** [comment]
should this be in assemblyscript repo? This is asc issue

**Comment by vgrichina** [comment]
yeah, I forgot we already started tracking issues in our fork
