### ISSUE TITLE
Near login hangs

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/near-shell#147]
1. Trying to login using `near login`
2. Go to wallet with the URL. Authorize the key. Success.
3. Go back to the console. Enter `eugenethedream`. Click enter
4. Hangs.
```
[WARNING] Didn't find config at /Users/h3r0k1ll3r/code/react/near-plus/src/config, using default shell config
Please navigate to this url and follow the instructions to log in:
https://wallet.nearprotocol.com/login/?title=NEAR+Shell&public_key=9x6Kej9oHMLFZ3qN76jZpvnxaNPfnLKrD2Lvr63DTgvt
Please enter the accountId that you logged in with:eugenethedream
Failed to load master account key from /Users/h3r0k1ll3r/.near/validator_key.json: Error: ENOENT: no such file or directory, open '/Users/h3r0k1ll3r/.near/validator_key.json'
(node:30236) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /usr/local/lib/node_modules/near-shell/index.js:141:35
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:30236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by evgenykuzyakov** [comment]
Seems it's for the old version `0.9.1`

**Comment by evgenykuzyakov** [comment]
Actually to check the version run `near --version`.
