### ISSUE TITLE
Error:  TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-shell#156]
Start local node using staging branch from nearcore:
```
rm -rf testdir; ./scripts/start_unittest.py --local
```

Make sure the most recent near-shell is installed:
```
npm install -g near-shell
```
At the time of reporting it is: `0.10.5`.

Create new project:
```
near new_project ./myproject; cd ./myproject
```
Edit `src/config.js` to have: `nodeUrl: 'http://localhost:3030',`.

Try creating new account:
```
near create_account cross_contract --masterAccount=test.near --homeDir=../../../../nearcore/testdir
```
You would need to modify `homeDir` path.
Observe the error message:
```
Error:  TypeError: Cannot read property 'reduce' of undefined
    at Account.signAndSendTransaction (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:84:46)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async LocalAccountCreator.createAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account_creator.js:16:9)
    at async Near.createAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/near.js:41:9)
    at async Object.exports.createAccount (/usr/local/lib/node_modules/near-shell/index.js:66:5)
    at async exitOnError (/usr/local/lib/node_modules/near-shell/bin/near:8:5)
```

**Comment by vgrichina** [comment]
@nearmax I think this is getting fixed by https://github.com/nearprotocol/nearlib/pull/80

**Comment by kcole16** [comment]
Closing as we removed `new_project` command from `near-shell`. Assuming this is in [create-near-app](https://github.com/nearprotocol/create-near-app) now?

**Comment by vgrichina** [comment]
> Assuming this is in create-near-app now?

yes
