### ISSUE TITLE
Getting invalid curve id 208 on staking tx

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#165]
```
near stake sparkpool ed25519:3ACSUZgqBHtpUyycqRmZe8yg1QgERpc7MzmihGS7kB8zfw 100000000000
[WARNING] Didn't find config at /root/src/config, using default shell config
Staking 100000000000 on sparkpool with public key = ed25519:3ACSUZgqBHtpUyycqRmZe8yg1QgERpc7MzmihGS7kB8zfw.
Error:  Error: [-32602] Invalid params: Failed to decode transaction: Unknown curve id 208
    at JsonRpcProvider.sendJsonRpc (/root/.nvm/versions/node/v10.0.0/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:49:19)
    at process._tickCallback (internal/process/next_tick.js:178:7)
...
```

**Comment by ilblackdragon** [comment]
Steps to repro:
`near login`
Copy the public key form the url and replace %3 with : when using in `near stake <username> <public key> 1`
Observe unknown curve id

**Comment by icerove** [comment]
now when logged in successfully, it will show Logged in as {accountId} with public key {public-key (ed25519:CV16URecQ1jshXQxzBRZStywfFBCuAVFyFYk39ngohuh)} successfully. so just copy this one. the url one actually transfer`:` into `%3A`, so should replace `%3A` not `%3`
