### ISSUE TITLE
Dev deploy gets rent unpaid due to not enough balance

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#271]
When calling `dev-deploy` received an error that RentUnpaid:
Probably not enough NEAR attached to the transaction:

```
near dev-deploy res/linkdrop.wasm --masterAccount illia.china --keyPath ../near-evm/neardev/default/illia.china.json
{
  networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com'
}
Loaded master account illia.china key from ../near-evm/neardev/default/illia.china.json with public key = ed25519:qSq3LoufLvTCTNGC3LJePMDGrok8dHMQ5A1YD9psbiz

Error:  TypedError: Transaction B4XPv4BMiuDX8fxjk79tqMeCquB2TFVFcjtxUqiRHPnP failed. The account dev-1582184616033 wouldn't have enough balance to pay required rent 10920
    at Account.signAndSendTransaction (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:84:23)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async LocalAccountCreator.createAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account_creator.js:17:9)
    at async createDevAccountIfNeeded (/usr/local/lib/node_modules/near-shell/commands/dev-deploy.js:62:5)
    at async devDeploy (/usr/local/lib/node_modules/near-shell/commands/dev-deploy.js:34:23)
    at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  type: 'ActionError::RentUnpaid'
}
```

**Comment by mikedotexe** [comment]
Closing as it was an issue in `nearlib` that was fixed here:
https://github.com/nearprotocol/nearlib/pull/249#event-3098739877
