### ISSUE TITLE
Near create_account reports unclear error when account already exists

### ISSUE THREAD

**Issue by ckshei** [nearprotocol/near-shell#52]
near create_account nearproject  
```
Error:  { BadRequestError: Transaction PwxM38gabyPbmtsi3RcOzvsDUwF/Lu9o6sjVbDnl4wQ= on unknown contract failed. 
    at sendJson (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/internal/send-json.js:12:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  message: 'Transaction PwxM38gabyPbmtsi3RcOzvsDUwF/Lu9o6sjVbDnl4wQ= on unknown contract failed. ' }
```

**Comment by janedegtiareva** [comment]
This works fine now e.g.
[janelocal]: Runtime error: Account unittest2 already exists
[ 'Runtime error: Account unittest2 already exists' ]
