### ISSUE TITLE
Error: URL is undefined on Node versions 9.x and before when running near login command

### ISSUE THREAD

**Issue by ckshei** [nearprotocol/near-shell#66]
Running near login with node version 9.0 gives error: 

{ networkId: 'default',
  nodeUrl: 'http://34.94.33.164:3030',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com' }
Error:  ReferenceError: URL is not defined
    at Object.exports.login (/usr/local/lib/node_modules/near-shell/index.js:122:24)
    at Object.handler (/usr/local/lib/node_modules/near-shell/bin/near:90:39)
    at Object.runCommand (/usr/local/lib/node_modules/near-shell/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/near-shell/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/near-shell/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/near-shell/bin/near:216:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)

**Comment by janedegtiareva** [comment]
fixed on master, will be available with next version
